#!/bin/bash

#Script written by christian.brenninkmeijer@manchester.ac.uk.

# -- SGE options (whose lines must begin with #$)

#$ -S /bin/bash       # Our jobscript is written for the bash shell
#$ -V                 # Inherit environment settings (e.g., from loaded modulefiles)
#$ -cwd               # Run the job in the current directory
#$ -pe smp.pe 4       # Example: 2 cores. Can specify 2-16. Do NOT use 1.
                      # Comment above line out for one core  

source /etc/profile.d/modules.sh
module load apps/trimmomatic/0.32/noarch  
echo module apps/trimmomatic/0.32/noarch  loaded
module load apps/gcc/rnastar/2.4.0 
echo module apps/gcc/rnastar/2.4.0 loaded
module load apps/htseq/0.6.1p1/gcc-4.4.7+python-2.7.5+numpy-1.7.1
echo module apps/htseq/0.6.1p1/gcc-4.4.7+python-2.7.5+numpy-1.7.1 loaded
module load apps libs/pysam/0.7.8/gcc-4.4.7+python-2.7.5
echo module apps libs/pysam/0.7.8/gcc-4.4.7+python-2.7.5 loaded

DIRECTORY=$1

# Go in to the directory
cd $DIRECTORY
pwd
ls -al



#TRIMMOMATIC
left_fastq=$(cat "left.link")
right_fastq=$(cat "right.link")

export TRIMMOMATIC_JAVA_OPTS="$TRIMMOMATIC_JAVA_OPTS \
-XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1"

run_command="trimmomatic PE -phred33 -threads $NSLOTS \
$left_fastq $right_fastq left_trimmed.fastq.gz left_unpaired.fastq.gz right_trimmed.fastq.gz right_unpaired.fastq.gz \
ILLUMINACLIP:/opt/gridware/pkg/apps/trimmomatic/0.32/noarch/share/adapters/TruSeq3-PE-2.fa:2:30:10 \
SLIDINGWINDOW:4:20 MINLEN:36"

echo running $run_command

$run_command
ls -al




#STAR
#As using /gz files
read_files_command="--readFilesCommand zcat"

#Delete all but required Option Default is SAM
#outputType="--outSAMtype BAM Unsorted SortedByCoordinate"
#outputType="--outSAMtype BAM SortedByCoordinate"
outputType="--outSAMtype BAM Unsorted"
#outputType="--outSAMtype SAM" 
    
run_command="STAR --runMode alignReads \
    --runThreadN $NSLOTS \
    --genomeLoad LoadAndKeep \
    --genomeDir /mnt/genome-shared-data/bcf/genomeIndexes/mm10_random_chrM_chrUn/STAR_gencodeM5 \
    --sjdbGTFfile /mnt/genome-shared-data/bcf/genomeIndexes/mm10_random_chrM_chrUn/annotation/Gencode-M5/gencode.vM5.annotation.gtf \
    --readFilesIn left_trimmed.fastq.gz right_trimmed.fastq.gz $read_files_command \
    $outputType"

echo running $run_command

$run_command
pwd
ls -al




#HTSeq
gff_file=/mnt/genome-shared-data/bcf/genomeIndexes/mm10_random_chrM_chrUn/annotation/Gencode-M5/gencode.vM5.annotation.gtf

#Parameters: See http://www-huber.embl.de/users/anders/HTSeq/doc/count.html#count

#Select relative sam is default
#format=--format=sam
format=--format=bam

#Select relative yes is default
#stranded=--stranded=yes       
stranded=--stranded=reverse   
#stranded=--stranded=no        

#Select relative exon is default
#WARNING: Listed Options may not work for all gff files files CHECK!
type=--type=exon
#type=--type=gene
#type=--type=transcript
#type=--type=CDS

#Select relative gene_id is default
#WARNING: Listed Options may not work for all gff files files CHECK!
idattr=--idattr=gene_id
#idattr=--idattr=transcript_id
#idattr=--idattr=gene_type
#idattr=--idattr=gene_name
#idattr=--idattr=transcript_type

run_command="python -m count $format $stranded $idattr $type Aligned.out.bam $gff_file"
echo running $run_command to htseq.output

$run_command > htseq.output
pwd
ls -al



