#!/bin/bash

#Script written by christian.brenninkmeijer@manchester.ac.uk.

# -- SGE options (whose lines must begin with #$)

#$ -S /bin/bash       # Our jobscript is written for the bash shell
#$ -V                 # Inherit environment settings (e.g., from loaded modulefiles)
#$ -cwd               # Run the job in the current directory
#$ -pe smp.pe 2       # Example: 2 cores. Can specify 2-16. Do NOT use 1.
                      # Comment above line out for one core  

module load apps/trimmomatic/0.32/noarch  

#codestart

inputpath=$1
secondpath=$2
outputdir=$3

mkdir -p $outputdir
if [ -d "$outputdir" ]; then
    echo Writing to $outputdir
else
    echo unable to create outputdir $outputdir
    exit -1
fi

file_name=${inputpath##*/}
dotindex=`expr index "$file_name" '.'` 
base=${file_name:0:$dotindex}
extension=${file_name:$dotindex}
trimmed1=${outputdir}/${base}_trimmed.${extension}
unpaired1=${outputdir}/${base}_unpaired.${extension}

file_name=${secondpath##*/}
dotindex=`expr index "$file_name" '.'` 
base=${file_name:0:$dotindex}
extension=${file_name:$dotindex}
trimmed2=${outputdir}/${base}_trimmed.${extension}
unpaired2=${outputdir}/${base}_unpaired.${extension}

echo export TRIMMOMATIC_JAVA_OPTS="$TRIMMOMATIC_JAVA_OPTS \
-XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1"

export TRIMMOMATIC_JAVA_OPTS="$TRIMMOMATIC_JAVA_OPTS 
-XX:ParallelGCThreads=1 -XX:ParallelCMSThreads=1"

echo trimmomatic PE -phred33 -threads $NSLOTS \
$inputpath $secondpath $trimmed1 $unpaired1 $trimmed2 $unpaired2 \
ILLUMINACLIP:/opt/gridware/pkg/apps/trimmomatic/0.32/noarch/share/adapters/TruSeq3-PE-2.fa:2:30:10 \
SLIDINGWINDOW:4:20 MINLEN:36 

trimmomatic PE -phred33 -threads $NSLOTS \
$inputpath $secondpath $trimmed1 $unpaired1 $trimmed2 $unpaired2 \
ILLUMINACLIP:/opt/gridware/pkg/apps/trimmomatic/0.32/noarch/share/adapters/TruSeq3-PE-2.fa:2:30:10 \
SLIDINGWINDOW:4:20 MINLEN:36 
